### ISSUE TITLE
Missing `env` folder

### ISSUE THREAD

**Issue by Jackmin801** [RoboEden/lux2-deimos#1]
您好,

The `agent.py` contains the following imports:
```python
from implementations.env.parsers.action_parser_full_act import ActionParser
from implementations.env.parsers.feature_parser import FeatureParser
from implementations.env.player import Player
```

There is however no `env` module in `implementations`
```bash
implementations/
├── impl_config.py
└── policy
    ├── actor_head.py
    ├── beta_binomial.py
    ├── impl
    │   ├── __init__.py
    │   └── multi_task_softmax_policy_impl.py
    ├── __init__.py
    ├── net.py
    └── simple_actor_head.py
```

Running the agent with `luxai-s2 main.py main.py -v 2 -o replay.json` thus results in 
```bash
ModuleNotFoundError: No module named 'implementations.env'
```

**Comment by Jackmin801** [comment]
The reason seems to be that `env/` is in the default gitignore
https://github.com/RoboEden/lux2-deimos/blob/master/.gitignore#L125

If you remove this line, you should be able to commit with the code.

**Comment by liqimai** [comment]
Thanks. We have added the `implementations.env` folder in 372a430.
